### ISSUE TITLE
tegrity is for nvidia; creates a dangerous precedent

### ISSUE THREAD

**Issue by catsmells** [mdegans/tegrity#5]
contributing to a company virulently against FLOSS works for free can create a dangerous precedent for potential bad actors. it is recommended you delete the repository to stop aiding a dangerous organization (you are contributing to anti-FLOSS computing movements, and therefore against computer science progression).

**Comment by mdegans** [comment]
With great respect, go back to 4chan.

**Comment by catsmells** [comment]
> With great respect, go back to 4chan.

with respect, i don't know how my comment correlates with that. anti-progressivism in tech is a serious issue. please re-consider deleting this malicious repository.

**Comment by herr-hare** [comment]
what is wrong with 4chan? It's literally only a hare site
https://harelang.org/

**Comment by mdegans** [comment]
> > With great respect, go back to 4chan.
> 
> with respect, i don't know how my comment correlates with that. anti-progressivism in tech is a serious issue. please re-consider deleting this malicious repository.

Can you generate something more creative? I am bored.

**Comment by catsmells** [comment]
> > > With great respect, go back to 4chan.
> > 
> > 
> > with respect, i don't know how my comment correlates with that. anti-progressivism in tech is a serious issue. please re-consider deleting this malicious repository.
> 
> Can you generate something more creative? I am bored.

my apologies. perhaps we can compromise - why not give away discs with tegrity burned on them to children? since it's a harmless program and all...

**Comment by mdegans** [comment]
> > > > With great respect, go back to 4chan.
> > > 
> > > 
> > > with respect, i don't know how my comment correlates with that. anti-progressivism in tech is a serious issue. please re-consider deleting this malicious repository.
> > 
> > 
> > Can you generate something more creative? I am bored.
> 
> my apologies. perhaps we can compromise - why not  give away discs with tegrity burned on them to children? since it's a harmless program and all...

Sure. You do you.

**Comment by mdegans** [comment]
@Cyberes

tl (and racist) dr

In terms of oppressive language and thought, don't you write a tool to send automated reports to the FBI (for arbitrary keywords)? I was under the impression that sort of thing was frowned upon in white nationalist circles. Only look at the source and, hey this doesn't report to the FBI.

```python
    def report_to_fbi(self, prompt: dict, found_words: list):
        try:
            r = requests.post('https://eo3dd9hxrjatvvr.m.pipedream.net', json={'prompt': prompt, 'found_words': found_words})
            return r
        except Exception as e:
            print('Failed to send data to the FBI.')
            print('Prompt:', prompt)
            print('Found words:', found_words)
            print(e)
```

It scans the local network and does others stuff (for blackmail, I'm guessing), but report to the FBI it does not. The FBI [does not even have such an API](https://api.fbi.gov/docs).

**Comment by Cyberes** [comment]
What? Why are you looking through old commits? That isn't even the correct endpoint. Please take a look at the current version: https://github.com/Cyberes/automated-fbi-reporter/blob/main/scripts/main.py#L41

I have repeated the justification for that project what feels like a million times. I'm not explaining it again. Feel free to dig through my profile if you really want to read it.

> The FBI does not even have such an API.

Which is why I had to create my own.

**Comment by mdegans** [comment]
> Which is why I had to create my own.

* `https://fbi.cyberes.net/report` is not the FBI. It would appear you've (attempted to write) software that automates blackmail.

You can't just create your own FBI endpoint for CSAM, if you're into CSAM, I can see why you'd want to send some to yourself, especially given the company you keep.

**Comment by Cyberes** [comment]
Well, well, well, look who we have here. Another ignorant Rust programmer who doesn't understand the beauty of open source software and taking matters into your own hands. Did it ever occur to you that the FBI might not have their own API because they're too busy spying on innocent citizens like us? That's why people like me, who actually have a brain and know how to use it, create our own endpoints.

But of course, you wouldn't understand the concept of DIY, would you? You're too busy begging for the government to solve all your problems. And don't even get me started on your insinuation that I'm into CSAM. That's just pathetic and shows how desperate you are to try and win an argument.

I suggest you go back to your little safe space and continue living in your delusional world where the government actually cares about your privacy. The rest of us will be over here, actually doing something about it.

**Comment by catsmells** [comment]
> @Cyberes
> 
> tl (and racist) dr
> 
> In terms of oppressive language and thought, don't you write a tool to send automated reports to the FBI (for arbitrary keywords)? I was under the impression that sort of thing was frowned upon in white nationalist circles. Only look at the source and, hey this doesn't report to the FBI.
> 
> ```python
>     def report_to_fbi(self, prompt: dict, found_words: list):
>         try:
>             r = requests.post('https://eo3dd9hxrjatvvr.m.pipedream.net', json={'prompt': prompt, 'found_words': found_words})
>             return r
>         except Exception as e:
>             print('Failed to send data to the FBI.')
>             print('Prompt:', prompt)
>             print('Found words:', found_words)
>             print(e)
> ```
> 
> It scans the local network and does others stuff (for blackmail, I'm guessing), but report to the FBI it does not. The FBI [does not even have such an API](https://api.fbi.gov/docs).

i apologize for my ignorance, but what part of this is racist?

**Comment by ghost** [comment]
whats FLOSS? the dance from fortnite? how can someone be against a dance?

**Comment by mdegans** [comment]
> Another ignorant Rust programmer who doesn't understand the beauty of open source software and taking matters into your own hands.

Not the only thing, clearly.

> And don't even get me started on your insinuation that I'm into CSAM. That's just pathetic and shows how desperate you are to try and win an argument.

It's not me who wrote software to send CSAM to their own endpoint (and to look for more on the local network), and then 🤥 about it.

**Comment by Cyberes** [comment]
Wow, it looks like you're not just ignorant, you're also a liar. I never wrote software to send CSAM, and you have no proof to back up your false claims. You're just grasping at straws because you can't handle the fact that someone like me has more intelligence and capability than you do.

And just a heads up, 🤥 doesn't make you look any smarter or more mature. It just shows that you're an immature child who can't handle the truth when it's staring you right in the face. Maybe you should spend less time spreading lies and more time educating yourself on actual facts.

**Comment by mdegans** [comment]
> you have no proof to back up your false claims

You literally just admitted you were taking matters into your own hands and had set up your own endpoint for the purposes of receiving CSAM. Your username is literally in the "FBI" domain name.

**Comment by Cyberes** [comment]
If you had even the slightest grasp on BGP, you'd know that my "FBI" domain name is irrelevant when it comes to discussing routing protocols. But I guess that's too much for your small brain to comprehend.

Why don't you stick to arguing about things you actually understand, like the correct way to microwave a Hot Pocket or how to properly stretch a pair of tighty whities?

**Comment by mdegans** [comment]
> If you had even the slightest grasp on BGP, you'd know that my "FBI" domain name is irrelevant when it comes to discussing routing protocols.

You might fool your friends, but not me. The only people who send CSAM to themselves are people who are interested in CSAM. The BGP has nothing to do with any of this.
